version: '3.3'

networks:
    custom:
        driver: bridge
        driver_opts:
            com.docker.network.driver.mtu: 1400
        ipam:
            driver: default
            config:
                -   subnet: "172.21.0.0/25"

services:

    postgres:
        container_name: postgres
        image: postgres:10.1-alpine
        environment:
            - POSTGRES_DB=call_center
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=12345
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            custom:
                aliases:
                    - postgres
                ipv4_address: "172.21.0.10"

    notary:
        container_name: notary
        image: corda/corda-zulu-5.0-snapshot:latest
        ports:
            - "10001:10001"
            - "10002:10002"
            - "10003:10003"
        volumes:
            - ../cordapp/build/nodes/Notary/certificates:/opt/corda/certificates
            - ../cordapp/build/nodes/Notary/additional-node-infos:/opt/corda/additional-node-infos
            - ../cordapp/build/nodes/Notary/network-parameters:/opt/corda/network-parameters
            - ../cordapp/build/nodes/Notary/node.conf:/etc/corda/node.conf
            - ../cordapp/build/nodes/Notary/cordapps:/opt/corda/cordapps
            - corda_notary:/opt/corda/persistence
#        restart: always
        networks:
            custom:
                aliases:
                    - notary
                ipv4_address: "172.21.0.2"

    agent:
        container_name: agent
        image: corda/corda-zulu-5.0-snapshot:latest
        ports:
            - "10004:10004"
            - "10005:10005"
            - "10006:10006"
        volumes:
            - ../cordapp/build/nodes/Agent/certificates:/opt/corda/certificates
            - ../cordapp/build/nodes/Agent/additional-node-infos:/opt/corda/additional-node-infos
            - ../cordapp/build/nodes/Agent/network-parameters:/opt/corda/network-parameters
            - ../cordapp/build/nodes/Agent/node.conf:/etc/corda/node.conf
            - ../cordapp/build/nodes/Agent/cordapps:/opt/corda/cordapps
            - corda_agent:/opt/corda/persistence
        networks:
            custom:
                aliases:
                    - agent
                ipv4_address: "172.21.0.3"

    api:
        container_name: api
        image: 685321914474.dkr.ecr.eu-west-3.amazonaws.com/orbita/call-center/api
        environment:
            - "JAVA_OPTS=-Xmx512m -DLogDir=/var/log/api -Dspring.config.location=/var/config/api/application.yml -Dfile.encoding=UTF8"
            - spring.http.encoding.charset=UTF-8
            - spring.http.encoding.enabled=true
            - spring.datasource.url=jdbc:postgresql://postgres:5432/call_center
            - config.rpc.agent-node.host=agent
        ports:
            - 9999:9999
        depends_on:
            - postgres
        networks:
            custom:
                aliases:
                    - api
                ipv4_address: "172.21.0.4"

volumes:
    pgdata:
    corda_notary:
    corda_agent:
