version: '3.3'

networks:
    custom:
        driver: bridge
        driver_opts:
            com.docker.network.driver.mtu: 1400

services:

    postgres:
        container_name: postgres
        image: postgres:10.1-alpine
        environment:
            - POSTGRES_DB=call_center
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=12345
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - custom

    api:
        container_name: api
        image: 685321914474.dkr.ecr.eu-west-3.amazonaws.com/orbita/call-center/api
        environment:
            - "JAVA_OPTS=-Xmx512m -DLogDir=/var/log/api -Dspring.config.location=/var/config/api/application.yml -Dfile.encoding=UTF8"
            - spring.http.encoding.charset=UTF-8
            - spring.http.encoding.enabled=true
            - spring.datasource.url=jdbc:postgresql://postgres:5432/call_center
            - config.rpc.agent-node.host=agent
        ports:
            - 9999:9999
        depends_on:
            - postgres
        networks:
            - custom

    notary:
        container_name: notary
        image: 685321914474.dkr.ecr.eu-west-3.amazonaws.com/orbita/call-center/corda-node:latest
        environment:
            - "JAVA_OPTS=-Xmx512m"
        ports:
            - "10001:10001"
            - "10002:10002"
            - "10003:10003"
        volumes:
            - corda_notary:/opt/corda
            - ../images/nodes/Notary/node.conf:/opt/corda/node.conf
            - ../cordapp/build/libs/cordapp-1.0-SNAPSHOT.jar:/opt/corda/cordapps/cordapp.jar
        networks:
            - custom
        depends_on:
            - networkmap
        restart: always

    agent:
        container_name: agent
        image: 685321914474.dkr.ecr.eu-west-3.amazonaws.com/orbita/call-center/corda-node:latest
        environment:
            - "JAVA_OPTS=-Xmx512m"
        ports:
            - "10004:10004"
            - "10005:10005"
            - "10006:10006"
        volumes:
            - corda_agent:/opt/corda
            - ../images/nodes/Agent/node.conf:/opt/corda/node.conf
            - ../cordapp/build/libs/cordapp-1.0-SNAPSHOT.jar:/opt/corda/cordapps/cordapp.jar
        networks:
            - custom
        depends_on:
            - networkmap
        restart: always

    networkmap:
        container_name: networkmap
        image: 685321914474.dkr.ecr.eu-west-3.amazonaws.com/orbita/pers-data/networkmap:latest
        environment:
            - "JAVA_OPTS=-Xmx512m -DLogDir=/var/log/networkmap -Dspring.config.location=/var/config/networkmap/application.yml"
        ports:
            - "8090:8090"
            - "8015:8015"
        networks:
            - custom
        restart: on-failure:3


volumes:
    pgdata:
    corda_notary:
    corda_agent:
